---
- name: Promote DC
  ansible.windows.win_domain_controller:
    dns_domain_name: "{{ win_deployseconddc_domain }}"
    domain_admin_password: "{{ win_deployseconddc_team_password }}"
    domain_admin_user: "{{ win_deployseconddc_netbios }}\\Administrator"
    safe_mode_password: "{{ win_deployseconddc_team_password }}"
    state: domain_controller
  register: dc_promo_result

- name: Reboot If Needed
  ansible.windows.win_reboot:
  when: dc_promo_result.reboot_required

- name: Set WinRM Back To Auto Start
  ansible.windows.win_service:
    name: WinRM
    start_mode: auto
