---
- name: Ensure Remote Management Group Exists
  ansible.windows.win_group:
    name: "Remote Management Users"
    state: present

- name: Set fDenyTSConnections
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword
    state: present

# The below was set whenever I changed this via settings
- name: Set updateRDStatus
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: updateRDStatus
    data: 1
    type: dword
    state: present

- name: Create RDP (TCP) Exception In Firewall (Windows > 7/2012)
  community.windows.win_firewall_rule:
    name: RDP
    protocol: tcp
    localport: 3389
    action: allow
    direction: in
    state: present
    profiles:
    - domain
    - private
    - public
    localip: any
    remoteip: any
    enabled: yes
  when: ansible_distribution_major_version|int > 6

- name: Create RDP (UDP) Exception in Firewall (Windows > 7/2012)
  community.windows.win_firewall_rule:
    name: RDP
    protocol: udp
    localport: 3389
    action: allow
    direction: in
    state: present
    profiles:
    - domain
    - private
    - public
    localip: any
    remoteip: any
    enabled: yes
  when: ansible_distribution_major_version|int > 6

- name: Create RDP Exception in Firewall (<= Windows 7/2012)
  ansible.windows.win_command: cmd.exe
  args:
    stdin: 'netsh advfirewall firewall set rule group="remote desktop" new enable=Yes'
  when: ansible_distribution_major_version|int <= 6
    