---
- name: Disable Autologin
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 0
    state: present
  register: autologin

- name: Remove Default Username
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    delete_key: no
    state: absent
  register: defaultusername

- name: Reboot if Needed
  ansible.windows.win_reboot:
  when: autologin.changed or defaultusername.changed
