---
- name: Create Working Directory
  ansible.builtin.include_tasks: set_working_dir.yaml
  
- name: Set Temp DNS
  ansible.builtin.include_tasks: set_dns.yaml 

- name: Ensure Chocolatey is Installed
  ansible.builtin.include_tasks: ensure_chocolatey.yaml
  
- name: Enable Firewall
  ansible.builtin.include_tasks: enable_firewall.yaml

- name: Enable ICMP
  ansible.builtin.include_tasks: allow_icmp.yaml

- name: Enable RDP
  ansible.builtin.include_tasks: allow_rdp.yaml

- name: Set Timezone
  ansible.builtin.include_tasks: set_timezone.yaml

- name: Set Hostname
  ansible.builtin.include_tasks: set_hostname.yaml

- name: Remove unattend.xml
  ansible.builtin.include_tasks: remove_unattend.yaml

- name: Disable Autologin
  ansible.builtin.include_tasks: disable_auto_login.yaml